version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: hotel_reservation_db
    environment:
      POSTGRES_DB: reservationdb
      POSTGRES_USER: reservationuser
      POSTGRES_PASSWORD: reservationpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: